services:
  - type: web
    name: lets-get-faded
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
